version: '2'

services:
  serviio:
    image: soerentsch/serviio:latest
    ports:
     - "1900:1900/udp"
     - "8895:8895/tcp"
     - "23423:23423/tcp"
     - "23424:23424/tcp"
    volumes:
     - /srv/docker/serviio/library:/opt/serviio/library
     - /srv/docker/serviio/plugins:/opt/serviio/plugins
     - /srv/docker/serviio/log:/opt/serviio/log